data_type: IEMOCAP
fusion_type: early_fusion
freeze_type: feature
is_augmentation: false
batch_size: 1
num_workers: 8
lr: 5.0e-05
max_epochs: 200
gpus:
- 1
strategy: ddp
local_rank: 0
num_nodes: 1
reproduce: false
